### ISSUE TITLE
 make more efficient use of space when posting to channels

### ISSUE THREAD

**Issue by bnfinet** [meedan/MantisBT-Slack#1]
in order to be a bit more succinct I'd suggest pairing down some of the information that's posted to the channel....

omit the headers (Severity Priority Assigned and Status) and combine their information onto one line as such....
@kratib, new, normal, minor

This is a little closer IMHO wrt the line printer/irc metaphor/twitter stream channel mechanisms of slack and could provide for easier scanning of multiple tickets being posted to the channel

**Comment by infojunkie** [comment]
Implemented in latest version.
